### ISSUE TITLE
Visual Studio 2015 build error

### ISSUE THREAD

**Issue by skn123** [clMathLibraries/clBLAS#177]
I am facing a build error with VS 2015

1>------ Build started: Project: tplgen (ExternalProjectTargets\tplgen\tplgen), Configuration: Release x64 ------
2>------ Skipped Build: Project: AutoGemm_Tools_Profile, Configuration: Release x64 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: AutoGemm_Tools_Test, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: GENERATE_CLT, Configuration: Release x64 ------
4>  TPLGEN Running.....
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/gemm.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\gemm.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/gemm_helper.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\gemm_helper.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/gbmv.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\gbmv.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/ger.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\ger.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/her.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\her.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/symm_helper.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\symm_helper.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/syr2_her2.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\syr2_her2.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/syr_her.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\syr_her.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/trsv.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\trsv.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/her2.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\her2.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/symm.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\symm.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/syr2.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\syr2.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/syr.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\syr.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/trmv.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\trmv.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/trsv_gemv.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\trsv_gemv.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/swap.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\swap.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/scal.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\scal.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/copy.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\copy.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/axpy.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\axpy.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dot.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dot.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/reduction.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\reduction.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/rotg.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\rotg.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/rotmg.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\rotmg.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/rotm.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\rotm.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/iamax.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\iamax.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/nrm2.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\nrm2.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/asum.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\asum.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/custom_gemm.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\custom_gemm.clT
4>CUSTOMBUILD : warning : couldn't open input file F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/custom_gemm.cl
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dgemm_hawai.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawai.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dgemm_hawaiiChannelConfilct.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawaiiChannelConfilct.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dgemm_hawaiiSplitKernel.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawaiiSplitKernel.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/sgemm_hawaiiSplitKernel.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_hawaiiSplitKernel.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dtrsm_gpu.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dtrsm_gpu.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dtrsm_gpu192.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dtrsm_gpu192.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/dgemm_gcn_SmallMatrices.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_gcn_SmallMatrices.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/sgemm_gcn_SmallMatrices.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_SmallMatrices.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/sgemm_gcn_bigMatrices.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_bigMatrices.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/sgemm_gcn.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn.clT
4>  Processing F:/GItSources/clBLAS/src/library/blas/gens/clTemplates/zgemm_gcn.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\zgemm_gcn.clT
4>  TPLGEN Running.....
4>  Processing /dgemm_hawai.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawai.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dgemm_hawai.clHawaii_64.bin.cl
4>  Processing /dtrsm_gpu.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dtrsm_gpu.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dtrsm_gpu.clHawaii_64.bin.cl
4>  Processing /dtrsm_gpu192.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dtrsm_gpu192.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dtrsm_gpu192.clHawaii_64.bin.cl
4>  Processing /dgemm_hawaiiChannelConfilct.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawaiiChannelConfilct.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dgemm_hawaiiChannelConfilct.clHawaii_64.bin.cl
4>  Processing /dgemm_hawaiiSplitKernel.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawaiiSplitKernel.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dgemm_hawaiiSplitKernel.clHawaii_64.bin.cl
4>  Processing /sgemm_hawaiiSplitKernel.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_hawaiiSplitKernel.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_hawaiiSplitKernel.clHawaii_64.bin.cl
4>  Processing /sgemm_hawaiiSplitKernel.clBonaire_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_hawaiiSplitKernel.clBonaire_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_hawaiiSplitKernel.clBonaire_64.bin.cl
4>  Processing /dgemm_hawai.clTahiti_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_hawai.clTahiti_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dgemm_hawai.clTahiti_64.bin.cl
4>  Processing /dtrsm_gpu.clTahiti_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dtrsm_gpu.clTahiti_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dtrsm_gpu.clTahiti_64.bin.cl
4>  Processing /dgemm_gcn_SmallMatrices.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_gcn_SmallMatrices.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dgemm_gcn_SmallMatrices.clHawaii_64.bin.cl
4>  Processing /dgemm_gcn_SmallMatrices.clTahiti_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\dgemm_gcn_SmallMatrices.clTahiti_64.bin.clT
4>  Processing /sgemm_gcn_SmallMatrices.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_SmallMatrices.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /dgemm_gcn_SmallMatrices.clTahiti_64.bin.cl
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn_SmallMatrices.clHawaii_64.bin.cl
4>  Processing /sgemm_gcn_SmallMatrices.clTahiti_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_SmallMatrices.clTahiti_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn_SmallMatrices.clTahiti_64.bin.cl
4>  Processing /sgemm_gcn_SmallMatrices.clBonaire_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_SmallMatrices.clBonaire_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn_SmallMatrices.clBonaire_64.bin.cl
4>  Processing /sgemm_gcn_bigMatrices.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_bigMatrices.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn_bigMatrices.clHawaii_64.bin.cl
4>  Processing /sgemm_gcn_bigMatrices.clTahiti_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_bigMatrices.clTahiti_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn_bigMatrices.clTahiti_64.bin.cl
4>  Processing /sgemm_gcn_bigMatrices.clBonaire_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn_bigMatrices.clBonaire_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn_bigMatrices.clBonaire_64.bin.cl
4>  Processing /sgemm_gcn.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn.clHawaii_64.bin.cl
4>  Processing /zgemm_gcn.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\zgemm_gcn.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /zgemm_gcn.clHawaii_64.bin.cl
4>  Processing /sgemm_gcn.clBonaire_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn.clBonaire_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn.clBonaire_64.bin.cl
4>  Processing /sgemm_gcn.clTahiti_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_gcn.clTahiti_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_gcn.clTahiti_64.bin.cl
4>  Processing /sgemm_hawaiiSplit64_32.clHawaii_64.bin.cl
4>  output file G:/Binaries/VS2015/clBLAS/include\sgemm_hawaiiSplit64_32.clHawaii_64.bin.clT
4>CUSTOMBUILD : warning : couldn't open input file /sgemm_hawaiiSplit64_32.clHawaii_64.bin.cl
5>------ Build started: Project: clBLAS, Configuration: Release x64 ------
6>------ Build started: Project: tune, Configuration: Release x64 ------
5>  Building Custom Rule F:/GItSources/clBLAS/src/library/CMakeLists.txt
5>  CMake does not need to re-run because G:\Binaries\VS2015\clBLAS\library\CMakeFiles\generate.stamp is up-to-date.
5>  Generating ../include/AutoGemmIncludes/AutoGemmClKernels.h, ../include/AutoGemmIncludes/AutoGemmKernelBuildOptionsBinary.h, ../include/AutoGemmIncludes/AutoGemmKernelBinaries.h, ../include/AutoGemmIncludes/AutoGemmKernelSelection.h, ../include/AutoGemmIncludes/AutoGemmKernelSelectionSpecific.h, ../include/AutoGemmIncludes/AutoGemmKernelBuildOptionsSource.h, ../include/AutoGemmIncludes/AutoGemmKernelSources.h, F:/GItSources/clBLAS/src/library/blas/AutoGemm/UserGemmKernelSources/UserGemmClKernels.cc, ../include/AutoGemmIncludes/AutoGemmClKernels.cpp, ../include/AutoGemmIncludes/AutoGemmKernelBuildOptionsBinary.cpp, ../include/AutoGemmIncludes/AutoGemmKernelBinaries.cpp, ../include/AutoGemmIncludes/AutoGemmKernelSelection.cpp, ../include/AutoGemmIncludes/AutoGemmKernelSelectionSpecific.cpp, ../include/AutoGemmIncludes/AutoGemmKernelBuildOptionsSource.cpp, ../include/AutoGemmIncludes/AutoGemmKernelSources.cpp
5>  AutoGemm.py: using OpenCL 1.2 compiler
5>  Traceback (most recent call last):
5>    File "F:/GItSources/clBLAS/src/library/blas/AutoGemm/AutoGemm.py", line 44, in <module>
5>      KernelOpenCL.writeOpenCLKernels()
5>    File "F:\GItSources\clBLAS\src\library\blas\AutoGemm\KernelOpenCL.py", line 506, in writeOpenCLKernels
5>      tiles = AutoGemmParameters.getTilesForPrecision(precision)
5>    File "F:\GItSources\clBLAS\src\library\blas\AutoGemm\AutoGemmParameters.py", line 123, in getTilesForPrecision
5>      tiles.sort()
5>  TypeError: unorderable types: TileParameters() < TileParameters()
5>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
6>  asum.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\asum.cpp(201): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>F:\GItSources\clBLAS\src\library\blas\gens\asum.cpp(257): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
6>  axpy_reg.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\axpy_reg.cpp(195): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>  copy_reg.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\copy_reg.cpp(195): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>  dot.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\dot.cpp(198): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>F:\GItSources\clBLAS\src\library\blas\gens\dot.cpp(254): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
6>F:\GItSources\clBLAS\src\library\blas\gens\dot.cpp(280): warning C4267: '=': conversion from 'size_t' to 'cl_int', possible loss of data
6>  gbmv.cpp
6>  gemm_cached.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(340): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(340): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(341): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(341): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(342): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(342): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(343): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(343): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(344): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(344): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(347): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(347): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(348): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_cached.cpp(348): note: consider using '%zu' in the format string
6>  gemm_tail_cached.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(349): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(349): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(350): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(350): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(351): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(351): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(352): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(352): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(353): warning C4477: 'sprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\gemm_tail_cached.cpp(353): note: consider using '%zu' in the format string
6>  ger_lds.cpp
6>  her2_lds.cpp
6>  her_lds.cpp
6>  iamax.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\iamax.cpp(260): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
6>  nrm2.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\nrm2.cpp(203): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>F:\GItSources\clBLAS\src\library\blas\gens\nrm2.cpp(252): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
6>  reduction.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\reduction.cpp(269): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
6>  rotg_reg.cpp
6>  rotm_reg.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\rotm_reg.cpp(192): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>  rotmg_reg.cpp
6>  scal_reg.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\scal_reg.cpp(191): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>  swap_reg.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\swap_reg.cpp(195): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
6>  symm_cached.cpp
6>  syr2_lds.cpp
6>  Generating Code...
6>  Compiling...
6>  syr_lds.cpp
6>  trmv_reg.cpp
6>  trsv_gemv.cpp
6>  trsv_trtri.cpp
6>F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(227): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'const size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(227): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(236): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'const size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(236): note: consider using '%zu' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(364): warning C4477: 'sprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'const size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(364): note: consider using '%zd' in the format string
6>F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(541): warning C4477: 'sprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'const size_t'
6>  F:\GItSources\clBLAS\src\library\blas\gens\trsv_trtri.cpp(541): note: consider using '%zd' in the format string
6>  Generating Code...
6>  tune.vcxproj -> G:\Binaries\VS2015\clBLAS\staging\Release\clBLAS-tune.exe
7>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: PACKAGE, Configuration: Release x64 ------
8>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 1 failed, 2 up-to-date, 4 skipped ==========

I think this is a Python related issue. I have Python 3.5 but these files were written for Python 2.7(??)

**Comment by skn123** [comment]
When I switched to Tag 2.6 it builds fine; albeit I had to comment out one line in msvc.h

**Comment by TimmyLiu** [comment]
2.6 was not tested under VS 2015. But it also does not need python to generate code.
2.8 was tested under VS 2015, but only with python 2.7. 
Can you by any chance try to build 2.8 with python 2.7?

**Comment by skn123** [comment]
Unfortunately, I can't. We only have Py 3.4 installed. I think these are simple issues related with Python syntax

**Comment by TimmyLiu** [comment]
Ok. I will rename this issue to python 3 support. Is that alright with you?

**Comment by hughperkins** [comment]
Observation: perhaps you can make code generation into an optional maintainers step, and commit the generated python code into the repository?  (You could provide an option in ccmake to turn auto-generation on).  This way, you reduce the number of build dependencies.

**Comment by skn123** [comment]
I agree with that suggestion

**Comment by MajorBreakfast** [comment]
When I tried to build (also VS2015 BTW) I got:
```
3>    File "C:/3rdparty/sources/clBLAS/src/library/blas/AutoGemm/AutoGemm.py", line 39
3>print "AutoGemm.py : warning : No output path specified; default is working directory."
3>                                                                                          ^
3>  SyntaxError: Missing parentheses in call to 'print'
```
I had to change my python in the `Path` environment variable to python 2.

You should mention (crappy old :-) python 2 as a requirement in the `README`. However, I agree with the others that the best solution would to make it optional. Not every c++ know his python :)
